# Total build timeout
timeout: '1800s' # 30 minutes

steps:
# 1. Build and push the container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA', '.']
  timeout: '1200s'    
# 2. Push the container image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ['push', 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA']
# 2. Deploy the container to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'library-management-system'
    - '--image=gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'
    # CORRECTED: This now correctly lists the NAMES of the secrets to remove.
    # This is needed to transition them from secret-references to plain-text env vars.
    - '--remove-secrets=SECRET_KEY,DATABASE_URL,EMAIL_HOST_PASSWORD,REDIS_URL'
    - '--clear-env-vars=SECRET_KEY,DATABASE_URL,EMAIL_HOST_PASSWORD,REDIS_URL'
    # IMPROVED: Using a different delimiter (^) makes the command robust
    # and prevents errors from special characters in your variables.
    - '--set-env-vars=^--^DEBUG=False--SECRET_KEY=${_SECRET_KEY}--ALLOWED_HOSTS=${_ALLOWED_HOSTS}--DATABASE_URL=${_DATABASE_URL}--EMAIL_BACKEND=${_EMAIL_BACKEND}--EMAIL_HOST=${_EMAIL_HOST}--EMAIL_PORT=${_EMAIL_PORT}--EMAIL_USE_TLS=${_EMAIL_USE_TLS}--EMAIL_HOST_USER=${_EMAIL_HOST_USER}--EMAIL_HOST_PASSWORD=${_EMAIL_HOST_PASSWORD}--DEFAULT_FROM_EMAIL=${_DEFAULT_FROM_EMAIL}--LIBRARY_NAME=${_LIBRARY_NAME}--LIBRARY_EMAIL=${_LIBRARY_EMAIL}--LIBRARY_PHONE=${_LIBRARY_PHONE}--LIBRARY_ADDRESS=${_LIBRARY_ADDRESS}--DAILY_FINE_AMOUNT=${_DAILY_FINE_AMOUNT}--MAX_FINE_AMOUNT=${_MAX_FINE_AMOUNT}--BORROWING_PERIOD_DAYS=${_BORROWING_PERIOD_DAYS}--RESERVATION_PERIOD_DAYS=${_RESERVATION_PERIOD_DAYS}--REDIS_URL=${_REDIS_URL}'
options:
  logging: CLOUD_LOGGING_ONLY
# Store the final image in Container Registry
images:
- 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA'

# --- CONFIGURATION VARIABLES ---
# For production, move sensitive values to Google Secret Manager.
substitutions:
  _REGION: 'us-central1'

  # Environment Variables
  # 🚨 WARNING: Storing secrets here is insecure. This is for testing only.
  _SECRET_KEY: 'django-insecure-ToQoNK7BG-I-1-g-eqW-pD5-Qbz-oBS-B-DZbRyKm-e-Yl-n'
  # Set to '*' for testing to allow any hostname.
  _ALLOWED_HOSTS: '*'
  _DATABASE_URL: 'sqlite:///db.sqlite3'
  _EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
  _EMAIL_HOST: 'smtp.gmail.com'
  _EMAIL_PORT: '587'
  _EMAIL_USE_TLS: 'True'
  _EMAIL_HOST_USER: 'helpdesk.rdi@gmail.com'
  # 🚨 WARNING: This is an app password and should be in Secret Manager.
  _EMAIL_HOST_PASSWORD: 'jdtonlzsskoimibg'
  _DEFAULT_FROM_EMAIL: 'helpdesk.rdi@gmail.com'
  _LIBRARY_NAME: 'NTA Library'
  _LIBRARY_EMAIL: 'helpdesk.rdi@gmail.com'
  _LIBRARY_PHONE: '+1234567890'
  _LIBRARY_ADDRESS: '123_Library_Street_City_State_12345'
  _DAILY_FINE_AMOUNT: '1.00'
  _MAX_FINE_AMOUNT: '50.00'
  _BORROWING_PERIOD_DAYS: '14'
  _RESERVATION_PERIOD_DAYS: '7'
  _REDIS_URL: 'redis://localhost:6379/0'