# Total build timeout
timeout: '1800s' # 30 minutes

steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA', '.']
  timeout: '1200s'

# 2. Push the container image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ['push', 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA']

# 3. Deploy new revision to Cloud Run with NO traffic
# This step safely stages the new version without making it live.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy Revision'
  entrypoint: gcloud
  args: >-
    run deploy library-management-system
    --image=gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA
    --region=${_REGION}
    --platform=managed
    --no-traffic
    --service-account=${_RUN_SERVICE_ACCOUNT}
    --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE_NAME}
    --vpc-connector=${_VPC_CONNECTOR_NAME}
    --set-env-vars=DEBUG=False,ALLOWED_HOSTS=${_ALLOWED_HOSTS},EMAIL_BACKEND=${_EMAIL_BACKEND},EMAIL_HOST=${_EMAIL_HOST},EMAIL_PORT=${_EMAIL_PORT},EMAIL_USE_TLS=${_EMAIL_USE_TLS},EMAIL_HOST_USER=${_EMAIL_HOST_USER},DEFAULT_FROM_EMAIL=${_DEFAULT_FROM_EMAIL},LIBRARY_NAME=${_LIBRARY_NAME},LIBRARY_EMAIL=${_LIBRARY_EMAIL},LIBRARY_PHONE=${_LIBRARY_PHONE},LIBRARY_ADDRESS=${_LIBRARY_ADDRESS},DAILY_FINE_AMOUNT=${_DAILY_FINE_AMOUNT},MAX_FINE_AMOUNT=${_MAX_FINE_AMOUNT},BORROWING_PERIOD_DAYS=${_BORROWING_PERIOD_DAYS},RESERVATION_PERIOD_DAYS=${_RESERVATION_PERIOD_DAYS}
    --set-secrets=SECRET_KEY=django-secret-key:latest,DATABASE_URL=db-connection-string:latest,EMAIL_HOST_PASSWORD=gmail-app-password:latest,REDIS_URL=redis-connection-string:latest

# 4. Run database migrations using a Cloud Run Job
# This runs migrations against the newly deployed (but not yet live) revision's environment.
# The build will fail here if migrations fail, preventing a broken release.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Migrate Database'
  entrypoint: gcloud
  args:
    - 'run'
    - 'jobs'
    - 'execute'
    - '${_MIGRATE_JOB_NAME}'
    - '--region=${_REGION}'
    - '--wait' # Wait for the migration to complete before proceeding

# 5. Switch traffic to the new revision
# This step only runs if the migration in the previous step was successful.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Switch Traffic'
  entrypoint: gcloud
  args:
    - 'run'
    - 'services'
    - 'update-traffic'
    - 'library-management-system'
    - '--to-latest'
    - '--region=${_REGION}'

# Store the final image in Container Registry
images:
- 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA'

# Logging configuration
options:
  logging: CLOUD_LOGGING_ONLY

# --- CONFIGURATION VARIABLES ---
# Replace the values below with your specific configuration.
# DO NOT store secrets here. Use Secret Manager.
substitutions:
  _REGION: 'us-central1'
  _MIGRATE_JOB_NAME: 'library-management-system-migrate'
  _RUN_SERVICE_ACCOUNT: 'your-cloud-run-runtime-sa@your-project-id.iam.gserviceaccount.com' # Recommended to not use the default
  _CLOUD_SQL_INSTANCE_NAME: 'your-project:your-region:your-instance'
  _VPC_CONNECTOR_NAME: 'your-vpc-connector-name'

  # Environment Variables (Non-secret)
  _ALLOWED_HOSTS: 'your-cloud-run-url.a.run.app,library.yourdomain.com' # Comma-separated
  _EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
  _EMAIL_HOST: 'smtp.gmail.com'
  _EMAIL_PORT: '587'
  _EMAIL_USE_TLS: 'True'
  _EMAIL_HOST_USER: 'your-email@gmail.com'
  _DEFAULT_FROM_EMAIL: 'your-email@gmail.com'
  _LIBRARY_NAME: 'NTA Library'
  _LIBRARY_EMAIL: 'library@nta.edu'
  _LIBRARY_PHONE: '+1234567890'
  _LIBRARY_ADDRESS: '123 Library Street, City, State 12345'
  _DAILY_FINE_AMOUNT: '1.00'
  _MAX_FINE_AMOUNT: '50.00'
  _BORROWING_PERIOD_DAYS: '14'
  _RESERVATION_PERIOD_DAYS: '7'
  _REDIS_URL: 'redis://10.0.0.1:6379/0'

# You can set these values in the Cloud Build trigger configuration
# or override them when manually triggering a build

# Set a timeout for the entire build process (30 minutes)
