steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'library-management-system'
  - '--image'
  - 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - |
    DEBUG=False,
    SECRET_KEY=${_SECRET_KEY},
    ALLOWED_HOSTS=${_ALLOWED_HOSTS},
    DATABASE_URL=${_DATABASE_URL},
    EMAIL_BACKEND=${_EMAIL_BACKEND},
    EMAIL_HOST=${_EMAIL_HOST},
    EMAIL_PORT=${_EMAIL_PORT},
    EMAIL_USE_TLS=${_EMAIL_USE_TLS},
    EMAIL_HOST_USER=${_EMAIL_HOST_USER},
    EMAIL_HOST_PASSWORD=${_EMAIL_HOST_PASSWORD},
    DEFAULT_FROM_EMAIL=${_DEFAULT_FROM_EMAIL},
    LIBRARY_NAME=${_LIBRARY_NAME},
    LIBRARY_EMAIL=${_LIBRARY_EMAIL},
    LIBRARY_PHONE=${_LIBRARY_PHONE},
    LIBRARY_ADDRESS=${_LIBRARY_ADDRESS},
    DAILY_FINE_AMOUNT=${_DAILY_FINE_AMOUNT},
    MAX_FINE_AMOUNT=${_MAX_FINE_AMOUNT},
    BORROWING_PERIOD_DAYS=${_BORROWING_PERIOD_DAYS},
    RESERVATION_PERIOD_DAYS=${_RESERVATION_PERIOD_DAYS},
    REDIS_URL=${_REDIS_URL}

# Store images in Google Container Registry
images:
- 'gcr.io/$PROJECT_ID/library-management-system:$COMMIT_SHA'

# Substitution variables for environment variables
substitutions:
  _SECRET_KEY: 'your-secret-key-here'
  _ALLOWED_HOSTS: 'your-cloud-run-url.a.run.app,library.yourdomain.com'
  _DATABASE_URL: 'postgres://user:password@/dbname?host=/cloudsql/your-project:your-region:your-instance'
  _EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
  _EMAIL_HOST: 'smtp.gmail.com'
  _EMAIL_PORT: '587'
  _EMAIL_USE_TLS: 'True'
  _EMAIL_HOST_USER: 'your-email@gmail.com'
  _EMAIL_HOST_PASSWORD: 'your-app-password'
  _DEFAULT_FROM_EMAIL: 'your-email@gmail.com'
  _LIBRARY_NAME: 'NTA Library'
  _LIBRARY_EMAIL: 'library@nta.edu'
  _LIBRARY_PHONE: '+1234567890'
  _LIBRARY_ADDRESS: '123 Library Street, City, State 12345'
  _DAILY_FINE_AMOUNT: '1.00'
  _MAX_FINE_AMOUNT: '50.00'
  _BORROWING_PERIOD_DAYS: '14'
  _RESERVATION_PERIOD_DAYS: '7'
  _REDIS_URL: 'redis://10.0.0.1:6379/0'

# You can set these values in the Cloud Build trigger configuration
# or override them when manually triggering a build