# Generated by Django 4.1.2 on 2022-10-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10)),
                ('shelve', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=100)),
                ('borrowing', models.CharField(max_length=100)),
                ('Dewey_Code', models.FloatField(max_length=100)),
                ('Copy', models.IntegerField(max_length=10, null=True)),
                ('ISBN', models.CharField(max_length=56, null=True)),
                ('Author', models.CharField(max_length=56, null=True)),
                ('Edition', models.CharField(max_length=56, null=True)),
                ('Pages', models.IntegerField(max_length=10, null=True)),
                ('Volume', models.CharField(max_length=56, null=True)),
                ('Series', models.CharField(max_length=56, null=True)),
                ('Publisher', models.CharField(max_length=56, null=True)),
                ('website', models.CharField(max_length=56, null=True)),
                ('Place_of_Publication', models.CharField(max_length=56, null=True)),
                ('Publication_Datte', models.IntegerField(max_length=10, null=True)),
                ('Editor', models.CharField(max_length=56, null=True)),
                ('Language', models.CharField(max_length=56, null=True)),
                ('Source', models.CharField(max_length=56, null=True)),
                ('Cover_Type', models.CharField(max_length=56, null=True)),
                ('Condition', models.CharField(max_length=56, null=True)),
                ('Main_Class', models.CharField(max_length=100, null=True)),
                ('Divisions', models.CharField(max_length=100, null=True)),
                ('Sections', models.CharField(max_length=100, null=True)),
                ('Cutter_Author', models.CharField(max_length=100, null=True)),
                ('Translator', models.CharField(max_length=100, null=True)),
                ('Book_Summary', models.TextField(null=True)),
                ('Contents', models.CharField(max_length=100, null=True)),
                ('Keywords', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=56)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('blacklisted', models.BooleanField()),
                ('borrower_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_borrower', to='books.book')),
                ('borrower_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_name', to='library_users.userprofileinfo')),
            ],
        ),
    ]
