# Generated by Django 4.1.4 on 2022-12-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Condition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Contents',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Cover_Type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Dewey_Code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Edition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Editor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Pages',
            field=models.IntegerField(max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Place_of_Publication',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publication_Datte',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Series',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='Volume',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='serial',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelve',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
