# Generated by Django 5.2.5 on 2025-09-12 20:50

from django.db import migrations
from django.utils.text import slugify


def populate_categories(apps, schema_editor):
    Category = apps.get_model('books', 'Category')
    categories_to_create = [
        "Fiction", "Science Fiction", "Fantasy", "Mystery", "Thriller",
        "Horror", "Historical Fiction", "Romance", "Young Adult", "Children's",
        "Biography", "Autobiography", "History", "Science", "Philosophy",
        "Self-Help", "Business", "Cookbooks", "Art", "Travel"
    ]
    for category_name in categories_to_create:
        slug = slugify(category_name)
        Category.objects.create(name=category_name, slug=slug)

def reverse_populate_categories(apps, schema_editor):
    Category = apps.get_model('books', 'Category')
    categories_to_delete = [
        "Fiction", "Science Fiction", "Fantasy", "Mystery", "Thriller",
        "Horror", "Historical Fiction", "Romance", "Young Adult", "Children's",
        "Biography", "Autobiography", "History", "Science", "Philosophy",
        "Self-Help", "Business", "Cookbooks", "Art", "Travel"
    ]
    for category_name in categories_to_delete:
        slug = slugify(category_name)
        Category.objects.filter(slug=slug).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_populate_categories)
    ]
