# Generated by Django 5.2.5 on 2025-09-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_populate_initial_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ISBN-13 format",
                max_length=17,
                null=True,
            ),
        ),
    ]
