# Generated by Django 4.2.7 on 2024-12-10 12:24

from django.db import migrations, models
import colorfield.fields
import django.core.cache


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_returnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Theme name (e.g., 'Default', 'Dark Mode', 'University Blue')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this theme')),
                ('is_active', models.BooleanField(default=False, help_text='Set as the active theme for the system')),
                ('primary_color', colorfield.fields.ColorField(default='#2563eb', help_text='Main brand color used for buttons, links, and accents', image_field=None, max_length=18, samples=None)),
                ('primary_dark', colorfield.fields.ColorField(default='#1d4ed8', help_text='Darker shade of primary color for hover states', image_field=None, max_length=18, samples=None)),
                ('primary_light', colorfield.fields.ColorField(default='#3b82f6', help_text='Lighter shade of primary color for backgrounds', image_field=None, max_length=18, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#64748b', help_text='Secondary color for less prominent elements', image_field=None, max_length=18, samples=None)),
                ('accent_color', colorfield.fields.ColorField(default='#f59e0b', help_text='Accent color for highlights and special elements', image_field=None, max_length=18, samples=None)),
                ('success_color', colorfield.fields.ColorField(default='#10b981', help_text='Color for success messages and positive actions', image_field=None, max_length=18, samples=None)),
                ('warning_color', colorfield.fields.ColorField(default='#f59e0b', help_text='Color for warning messages and caution states', image_field=None, max_length=18, samples=None)),
                ('danger_color', colorfield.fields.ColorField(default='#ef4444', help_text='Color for error messages and destructive actions', image_field=None, max_length=18, samples=None)),
                ('info_color', colorfield.fields.ColorField(default='#3b82f6', help_text='Color for informational messages', image_field=None, max_length=18, samples=None)),
                ('background_primary', colorfield.fields.ColorField(default='#ffffff', help_text='Main background color for pages', image_field=None, max_length=18, samples=None)),
                ('background_secondary', colorfield.fields.ColorField(default='#f8fafc', help_text='Secondary background color for sections', image_field=None, max_length=18, samples=None)),
                ('background_dark', colorfield.fields.ColorField(default='#1e293b', help_text='Dark background color for contrast areas', image_field=None, max_length=18, samples=None)),
                ('text_primary', colorfield.fields.ColorField(default='#1e293b', help_text='Primary text color', image_field=None, max_length=18, samples=None)),
                ('text_secondary', colorfield.fields.ColorField(default='#64748b', help_text='Secondary text color for less important text', image_field=None, max_length=18, samples=None)),
                ('text_muted', colorfield.fields.ColorField(default='#94a3b8', help_text='Muted text color for hints and placeholders', image_field=None, max_length=18, samples=None)),
                ('text_white', colorfield.fields.ColorField(default='#ffffff', help_text='White text color for dark backgrounds', image_field=None, max_length=18, samples=None)),
                ('border_color', colorfield.fields.ColorField(default='#e2e8f0', help_text='Color for borders and dividers', image_field=None, max_length=18, samples=None)),
                ('border_light', colorfield.fields.ColorField(default='#f1f5f9', help_text='Light border color', image_field=None, max_length=18, samples=None)),
                ('border_dark', colorfield.fields.ColorField(default='#cbd5e1', help_text='Dark border color', image_field=None, max_length=18, samples=None)),
                ('card_background', colorfield.fields.ColorField(default='#ffffff', help_text='Background color for cards and components', image_field=None, max_length=18, samples=None)),
                ('card_border', colorfield.fields.ColorField(default='#e2e8f0', help_text='Border color for cards', image_field=None, max_length=18, samples=None)),
                ('card_shadow', models.CharField(default='0 4px 6px -1px rgb(0 0 0 / 0.1)', help_text='CSS box-shadow value for cards', max_length=100)),
                ('button_radius', models.CharField(default='0.5rem', help_text="Border radius for buttons (e.g., '0.5rem', '8px')", max_length=20)),
                ('navbar_background', colorfield.fields.ColorField(default='#ffffff', help_text='Navigation bar background color', image_field=None, max_length=18, samples=None)),
                ('navbar_text', colorfield.fields.ColorField(default='#1e293b', help_text='Navigation bar text color', image_field=None, max_length=18, samples=None)),
                ('navbar_hover', colorfield.fields.ColorField(default='#f1f5f9', help_text='Navigation bar hover background color', image_field=None, max_length=18, samples=None)),
                ('footer_background', colorfield.fields.ColorField(default='#1e293b', help_text='Footer background color', image_field=None, max_length=18, samples=None)),
                ('footer_text', colorfield.fields.ColorField(default='#94a3b8', help_text='Footer text color', image_field=None, max_length=18, samples=None)),
                ('book_card_background', colorfield.fields.ColorField(default='#ffffff', help_text='Background color for book cards', image_field=None, max_length=18, samples=None)),
                ('book_card_border', colorfield.fields.ColorField(default='#e2e8f0', help_text='Border color for book cards', image_field=None, max_length=18, samples=None)),
                ('book_card_hover', colorfield.fields.ColorField(default='#f8fafc', help_text='Hover background color for book cards', image_field=None, max_length=18, samples=None)),
                ('book_available_color', colorfield.fields.ColorField(default='#10b981', help_text='Color indicator for available books', image_field=None, max_length=18, samples=None)),
                ('book_borrowed_color', colorfield.fields.ColorField(default='#f59e0b', help_text='Color indicator for borrowed books', image_field=None, max_length=18, samples=None)),
                ('book_overdue_color', colorfield.fields.ColorField(default='#ef4444', help_text='Color indicator for overdue books', image_field=None, max_length=18, samples=None)),
                ('dashboard_card_bg', colorfield.fields.ColorField(default='#ffffff', help_text='Dashboard card background color', image_field=None, max_length=18, samples=None)),
                ('dashboard_stat_primary', colorfield.fields.ColorField(default='#2563eb', help_text='Primary dashboard statistic color', image_field=None, max_length=18, samples=None)),
                ('dashboard_stat_success', colorfield.fields.ColorField(default='#10b981', help_text='Success dashboard statistic color', image_field=None, max_length=18, samples=None)),
                ('dashboard_stat_warning', colorfield.fields.ColorField(default='#f59e0b', help_text='Warning dashboard statistic color', image_field=None, max_length=18, samples=None)),
                ('dashboard_stat_danger', colorfield.fields.ColorField(default='#ef4444', help_text='Danger dashboard statistic color', image_field=None, max_length=18, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Configuration',
                'verbose_name_plural': 'Theme Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('theme_data', models.JSONField(help_text='JSON data containing all theme color values')),
                ('preview_image', models.ImageField(blank=True, help_text='Preview image of this theme', null=True, upload_to='theme_previews/')),
                ('is_built_in', models.BooleanField(default=False, help_text='Built-in themes cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Theme Preset',
                'verbose_name_plural': 'Theme Presets',
                'ordering': ['name'],
            },
        ),
    ]