# Generated by Django 5.2.5 on 2025-09-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="serial",
            field=models.CharField(
                help_text="Unique serial number for the book", max_length=20
            ),
        ),
    ]
