# Generated by Django 4.2.7 on 2024-12-10 13:16

from django.db import migrations
import colorfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_themeconfiguration_themepreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfiguration',
            name='accent_color',
            field=colorfield.fields.ColorField(default='#f59e0b', help_text='Accent color for highlights and special elements', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='themeconfiguration',
            name='background_dark',
            field=colorfield.fields.ColorField(default='#1e293b', help_text='Dark background color for contrast areas', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='themeconfiguration',
            name='background_primary',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Main background color for pages', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='themeconfiguration',
            name='background_secondary',
            field=colorfield.fields.ColorField(default='#f8fafc', help_text='Secondary background color for sections', image_field=None, max_length=18, samples=None),
        ),
    ]