# Generated by Django 4.1.4 on 2022-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InBoxMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
