# Generated by Django 4.1.4 on 2022-12-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_users', '0002_inboxmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InBoxMessages',
            new_name='Contact',
        ),
    ]
